services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      # Add 'args' to pass build-time environment variables
      # These values will be pulled from the .env.local file
      args:
        - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
        - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    container_name: entrypoint_webapp
    ports:
      - '3000:3000'
    # The 'env_file' directive loads environment variables from a file.
    env_file:
      - .env.local
    # We add an 'environment' section to set the internal URL.
    # This URL is used by the server-side parts of Next.js to communicate
    # with Supabase's API gateway (Kong) over the internal Docker network.
    environment:
      - SUPABASE_INTERNAL_URL=http://kong:8000
    networks:
      - supabase_network

networks:
  supabase_network:
    # This tells Docker Compose that the network is defined elsewhere.
    # In this case, it's the network created by the Supabase CLI.
    # Need to update setup process/docs to make this consistent across developer machines
    external: true
    name: supabase_network_entrypoint-webapp
