export type ContactInfo = {
  contactId: string;
  relationToStudent: string;
  firstName: string;
  lastName: string;
  email: string;
  phone: string;
};

export type StudentInfo = {
  studentId: string;
  schoolId: string;
  gpa?: number;
  firstName: string;
  middleName: string;
  lastName: string;
  fullName: string;
  photoUrl?: string;
  email: string;
  phone: string;
  gradeLevel: number;
  gender: string;
  dateOfBirth: Date | null;
  createdAt: Date;
  updatedAt: Date;
  externalSource: string;
  externalKey: string;
  externalId: string;
  externalKeyHash: string;
  externalName: string;
  graduationYear: number;
  enrollmentStatus: string;
  homeroomName: string;
  customerId: string;
  lunchId?: string;
  stateStudentNumber?: string;
  race?: string;
  addressPhysicalStreet?: string;
  addressPhysicalCity?: string;
  addressPhysicalState?: string;
  addressPhysicalPostalCode?: string;
  addressMailingStreet?: string;
  addressMailingCity?: string;
  addressMailingState?: string;
  addressMailingPostalCode?: string;
  studentNumber?: string;
  contacts?: ContactInfo[];
};